name: "Sonar_cloud"

on:
  workflow_dispatch:
  
jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarColud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ruksarnaj
            -Dsonar.projectKey=push-java
